apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: platform-services
  sources:
    - repoURL: 'oci://ghcr.io/nginx/charts/nginx-ingress'
      chart: nginx-ingress
      targetRevision: 2.4.1
      helm:
        releaseName: nginx-ingress
        valueFiles:
          - $values/helm/nginx-ingress/values.yaml
    - repoURL: 'https://github.com/githubadministrator01/devops-crash-course-cicd-k8s-helm-argo-actions.git'  # replace with your repo 
      targetRevision: main
      ref: values    
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nginx-ingress
  syncPolicy:
    syncOptions:
      - PruneLast=true     # prune resources in the last step
      - CreateNamespace=true  # automatically create namespace if missing
      - ServerSideApply=true  # use server-side apply for better merging